name: Test

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main
  merge_group:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.14"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv tool install . -e

      - name: Install test dependencies
        run: make install-test-deps

      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make test

      - name: Run instrumentation tests
        run: make test-instrumentation
